#!/usr/bin/env python3
"""Build the standalone GitHub Pages research laboratory."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

HTML = r'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Topology-aware streaming Bayesian nonparametric clustering of OpenSky aircraft kinematics.">
  <title>OpenSky Streaming DPMM Laboratory</title>
  <script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
  <style>
    :root{--bg:#050b14;--panel:#0b1826;--panel2:#0e2132;--line:#203e55;--text:#edf7ff;--muted:#90aec2;--cyan:#39d5ff;--mint:#63e6b2;--amber:#ffbe4d;--coral:#ff7d78;--violet:#a78bfa;--shadow:0 22px 70px rgba(0,0,0,.28)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 85% 0,#112c40 0,transparent 34%),var(--bg);color:var(--text);font:15px/1.65 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
    a{color:var(--cyan)}button,select,input{font:inherit}.shell{width:min(1240px,calc(100% - 28px));margin:auto}.top{position:sticky;top:0;z-index:20;background:rgba(5,11,20,.89);backdrop-filter:blur(18px);border-bottom:1px solid var(--line)}
    .nav{height:66px;display:flex;align-items:center;gap:18px}.brand{font-weight:900;letter-spacing:.08em;margin-right:auto}.brand i{display:inline-block;width:9px;height:9px;background:var(--cyan);border-radius:50%;box-shadow:0 0 18px var(--cyan);margin-right:9px}.tabs{display:flex;gap:4px;overflow:auto}.tab{border:0;background:transparent;color:var(--muted);padding:11px 13px;border-radius:9px;cursor:pointer;white-space:nowrap}.tab:hover,.tab.active{color:white;background:#10283b;box-shadow:inset 0 -2px var(--cyan)}
    .actions{display:flex;gap:8px}.btn{display:inline-flex;align-items:center;justify-content:center;border:1px solid #31536a;border-radius:9px;padding:9px 13px;color:white;text-decoration:none;font-weight:750;background:#091522}.btn.primary{background:var(--cyan);color:#00121a;border-color:var(--cyan)}
    main{padding:45px 0 70px}.hero{display:grid;grid-template-columns:1.35fr .65fr;gap:32px;align-items:center;margin-bottom:28px}.eyebrow{font-size:.74rem;color:var(--cyan);letter-spacing:.15em;font-weight:900;text-transform:uppercase}.hero h1{font-size:clamp(2.6rem,6vw,5.3rem);line-height:.97;letter-spacing:-.065em;margin:.28em 0}.lede{font-size:1.05rem;color:#c9dfed;max-width:780px}.boundary{border-left:3px solid var(--amber);background:linear-gradient(135deg,rgba(255,190,77,.12),rgba(255,190,77,.04));padding:20px;border-radius:0 12px 12px 0}.boundary strong{color:var(--amber)}
    .metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;margin:28px 0}.metric,.card{border:1px solid var(--line);background:linear-gradient(145deg,rgba(13,31,47,.96),rgba(7,18,29,.96));border-radius:14px;box-shadow:var(--shadow)}.metric{padding:18px 16px;min-height:100px;position:relative;overflow:hidden}.metric:after{content:"";position:absolute;width:64px;height:64px;border-radius:50%;right:-18px;top:-18px;background:rgba(57,213,255,.07)}.metric b{display:block;font-size:1.7rem;letter-spacing:-.04em}.metric span{font-size:.67rem;color:var(--muted);text-transform:uppercase;letter-spacing:.11em}.card{padding:24px;margin:14px 0}.card h2,.card h3{margin:0 0 6px;letter-spacing:-.025em}.sub{color:var(--muted);margin-top:0}.panel{display:none}.panel.active{display:block}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px}.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.mini{padding:17px;border:1px solid var(--line);background:#071421;border-radius:12px}.mini b{display:block;color:white}.mini p{color:#b5cddd;margin:.55rem 0 0}.status{display:inline-flex;align-items:center;border-radius:999px;padding:4px 8px;font-size:.67rem;font-weight:850;text-transform:uppercase;letter-spacing:.07em;background:rgba(99,230,178,.1);color:var(--mint)}.status.pending{color:var(--amber);background:rgba(255,190,77,.1)}
    .controls{display:flex;align-items:end;flex-wrap:wrap;gap:14px;margin:18px 0}.control{min-width:150px}.control label{display:block;color:var(--muted);font-size:.7rem;text-transform:uppercase;letter-spacing:.09em;margin-bottom:5px}.control input[type=range]{width:100%;accent-color:var(--cyan)}select{width:100%;background:#071421;color:white;border:1px solid #36546a;padding:9px;border-radius:8px}.readout{padding:11px 14px;border:1px solid var(--line);border-radius:9px;background:#06111c;min-width:130px}.readout b{color:var(--cyan)}
    .plot{width:100%;height:430px}.plot.tall{height:510px}.doe{display:grid;grid-template-columns:170px repeat(3,1fr);gap:8px;margin-top:18px}.doe div{padding:16px;border:1px solid var(--line);border-radius:10px;background:#071421}.doe .head{color:var(--cyan);font-weight:800;background:#0a2030}.doe .cell{cursor:pointer;transition:.18s}.doe .cell:hover,.doe .cell.selected{transform:translateY(-2px);border-color:var(--cyan);background:#0d2c40}.doe .cell b{display:block;font-size:1.35rem}.equation{font:1.05rem/1.6 Georgia,serif;background:#06121e;border-left:3px solid var(--violet);padding:18px 20px;overflow:auto}.ladder{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-top:18px}.gate{padding:17px;border:1px solid var(--line);border-radius:12px;background:#071421}.gate.complete{border-top:3px solid var(--mint)}.gate.pending{border-top:3px solid var(--amber)}.gate.blocked{border-top:3px solid var(--coral)}
    table{width:100%;border-collapse:collapse;margin-top:14px}th,td{text-align:left;padding:12px;border-bottom:1px solid var(--line);vertical-align:top}th{font-size:.68rem;text-transform:uppercase;letter-spacing:.1em;color:var(--muted)}.callout{border:1px solid rgba(99,230,178,.35);background:rgba(99,230,178,.07);padding:20px;border-radius:12px}.callout h3{color:var(--mint)}code,pre{font:13px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace}pre{background:#030a12;border:1px solid var(--line);padding:18px;border-radius:10px;overflow:auto;color:#bdefff}.footer{border-top:1px solid var(--line);padding:30px 0 46px;color:var(--muted);font-size:.8rem}.notice{font-size:.76rem;color:var(--muted)}
    @media(max-width:980px){.tabs{order:3;width:100%}.nav{height:auto;flex-wrap:wrap;padding:10px 0}.hero{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(3,1fr)}.grid3,.ladder{grid-template-columns:1fr 1fr}}
    @media(max-width:650px){.shell{width:min(100% - 18px,1240px)}.actions{display:none}.hero h1{font-size:3rem}.metrics,.grid2,.grid3,.ladder{grid-template-columns:1fr 1fr}.doe{grid-template-columns:100px repeat(3,1fr);font-size:.8rem}.doe div{padding:10px}.plot{height:360px}}
  </style>
</head>
<body>
<header class="top"><nav class="nav shell" aria-label="Primary"><div class="brand"><i></i>OPENSKY DPMM</div><div class="tabs" role="tablist">
  <button class="tab active" data-panel="dashboard">Dashboard</button><button class="tab" data-panel="manifold">Manifold</button><button class="tab" data-panel="truncation">DP truncation</button><button class="tab" data-panel="design">DOE</button><button class="tab" data-panel="diagnostics">Diagnostics</button><button class="tab" data-panel="validation">Validation</button><button class="tab" data-panel="resources">Report & code</button>
</div><div class="actions"><a class="btn" href="https://github.com/salemmorelli1/OpenSky-Streaming-DPMM">GitHub</a><a class="btn primary" href="report/OpenSky_Streaming_DPMM_APA_Report.pdf">Open report</a></div></nav></header>
<main class="shell">
  <section class="hero"><div><div class="eyebrow">Bayesian nonparametrics · circular statistics · streaming computation</div><h1>Open-world structure on <span style="color:var(--cyan)">R² × S¹.</span></h1><p class="lede">A corrected research laboratory for clustering public OpenSky aircraft kinematics when the number of latent behaviors is unknown, headings are periodic, and observation loss is controlled experimentally.</p></div><aside class="boundary"><strong>Exact claim boundary</strong><br>OpenSky supplies state vectors, not received radar pulses. This is an aviation-surveillance methodology study. No radar-emitter, ELINT, operational SIGINT, identity, intent, or threat-performance claim is made.</aside></section>
  <div class="metrics"><div class="metric"><b>R² × S¹</b><span>observation topology</span></div><div class="metric"><b>2</b><span>inference engines</span></div><div class="metric"><b>3</b><span>thinning levels</span></div><div class="metric"><b>100</b><span>planned blocks</span></div><div class="metric"><b>600</b><span>planned executions</span></div><div class="metric"><b>26</b><span>report pages</span></div></div>

  <section id="dashboard" class="panel active">
    <div class="card"><span class="status pending">Empirical benchmark pending</span><h2 style="margin-top:10px">Overall conclusion</h2><div class="callout"><h3>Methodological validity is established; comparative empirical validity is not yet estimated.</h3><p>The reconstructed project resolves the original API, topology, truncation, inference-target, diagnostic, and design contradictions. It now provides two coherent Bayesian nonparametric estimators on the correct product measure and a leakage-controlled six-cell protocol. The defensible conclusion at this release is therefore about <em>framework correctness and reproducibility</em>, not clustering superiority. Executing the 100 frozen OpenSky blocks is the remaining step required for method-effect estimates.</p></div></div>
    <div class="grid2"><div class="card"><h2>Evidence runway</h2><p class="sub">A claim can advance only when its evidence gate is complete.</p><div class="grid2"><div class="mini"><span class="status">Complete</span><b>Measure and topology</b><p>Density is defined against Lebesgue × Haar measure.</p></div><div class="mini"><span class="status">Complete</span><b>Dual inference</b><p>Residual-stick VI and collapsed DP-SMC are implemented.</p></div><div class="mini"><span class="status">Complete</span><b>Frozen protocol</b><p>Paired blocks, nested masks, and contrasts are specified.</p></div><div class="mini"><span class="status pending">Pending</span><b>OpenSky execution</b><p>No empirical endpoint is displayed before the locked run.</p></div></div></div><div class="card"><h2>Research problem</h2><p>The project asks whether online open-world clustering can remain stable under circular geometry, unknown cluster count, concept drift, and controlled observation loss. A closed-world label is not assumed during fitting.</p><div class="equation">Y<sub>t</sub> = (log(1 + speed<sub>t</sub>), asinh(vertical-rate<sub>t</sub>/5), heading<sub>t</sub>) ∈ R² × S¹</div><p class="notice">OpenSky category fields, when available, remain evaluator-only labels.</p></div></div>
    <div class="card"><h2>Inference architecture</h2><div class="grid3"><div class="mini"><b>1 · Record once</b><p>Freeze one API block with provenance and completeness metadata.</p></div><div class="mini"><b>2 · Couple treatments</b><p>Replay the same block through nested 0%, 15%, and 30% masks.</p></div><div class="mini"><b>3 · Fit blindly</b><p>Run both methods without identity or evaluation labels.</p></div><div class="mini"><b>4 · Diagnose</b><p>Track predictive score, latency, cluster count, and algorithmic health.</p></div><div class="mini"><b>5 · Unlock</b><p>Join evaluation-only labels after predictions are frozen.</p></div><div class="mini"><b>6 · Estimate</b><p>Fit the preregistered paired mixed-effects contrasts.</p></div></div></div>
  </section>

  <section id="manifold" class="panel"><div class="card"><h2>The circular cut disappears</h2><p class="sub">Move a heading across 360°. The raw degree coordinate jumps; geodesic and embedded representations remain continuous.</p><div class="controls"><div class="control" style="min-width:300px"><label for="heading">Heading</label><input id="heading" type="range" min="340" max="380" step=".25" value="359"></div><div class="readout">Raw: <b id="rawHeading">359°</b></div><div class="readout">Wrapped: <b id="wrappedHeading">359°</b></div><div class="readout">Arc to 0°: <b id="arcHeading">1°</b></div></div><div id="circlePlot" class="plot"></div></div><div class="grid2"><div class="card"><h2>Reference measure</h2><div class="equation">μ = λ<sub>R²</sub> ⊗ λ<sub>S¹</sub></div><p>The likelihood is a density with respect to two-dimensional Lebesgue measure and arc-length Haar measure. A full-rank Gaussian in the ambient cosine-sine embedding would assign mass off the circle and does not define the stated manifold model.</p></div><div class="card"><h2>Product kernel</h2><div class="equation">p(y | η) = N₂(x | μ, Λ⁻¹) · VM(θ | ψ, κ)</div><p>The Euclidean component uses Normal-Gamma uncertainty. The directional component uses a von Mises density normalized by 2πI₀(κ), eliminating artificial distance at the coordinate cut.</p></div></div></section>

  <section id="truncation" class="panel"><div class="card"><h2>Residual-stick truncation explorer</h2><p class="sub">For a DP with concentration α, the expected unallocated residual after K−1 sticks is [α/(1+α)]^(K−1).</p><div class="controls"><div class="control"><label for="alpha">Concentration α</label><input id="alpha" type="range" min="0.1" max="10" step="0.1" value="2"></div><div class="control"><label for="clusters">Truncation K</label><input id="clusters" type="range" min="2" max="40" step="1" value="15"></div><div class="readout">Residual: <b id="residual">—</b></div><div class="readout">Represented: <b id="represented">—</b></div></div><div id="stickPlot" class="plot"></div></div><div class="grid2"><div class="card"><h2>Correct construction</h2><p>Draw V₁,…,V<sub>K−1</sub> and set the final weight to the unbroken remainder. The implementation never draws a Kth beta stick and discards its remainder.</p></div><div class="card"><h2>Interpretation</h2><p>Truncation is a controlled approximation, not proof that the data contain K clusters. The explorer quantifies a prior expected residual; posterior occupancy and predictive adequacy must still be checked.</p></div></div></section>

  <section id="design" class="panel"><div class="card"><h2>Preregistered 2 × 3 factorial design</h2><p class="sub">Select a cell to inspect its paired experimental role. Each cell contains 100 frozen blocks.</p><div class="doe"><div class="head">Architecture</div><div class="head">0% thinning</div><div class="head">15% thinning</div><div class="head">30% thinning</div><div class="head">Streaming VI</div><div class="cell selected" data-method="VI" data-drop="0"><b>100</b>blocks</div><div class="cell" data-method="VI" data-drop="15"><b>100</b>blocks</div><div class="cell" data-method="VI" data-drop="30"><b>100</b>blocks</div><div class="head">Collapsed SMC</div><div class="cell" data-method="SMC" data-drop="0"><b>100</b>blocks</div><div class="cell" data-method="SMC" data-drop="15"><b>100</b>blocks</div><div class="cell" data-method="SMC" data-drop="30"><b>100</b>blocks</div></div><div class="callout" style="margin-top:16px"><h3 id="cellTitle">Streaming VI · 0% thinning</h3><p id="cellText">Baseline low-latency approximation on every eligible observation in each recorded block.</p></div></div><div class="grid2"><div class="card"><h2>Nested missingness control</h2><div id="maskPlot" class="plot"></div><p class="notice">Illustrative deterministic mask; actual masks are regenerated from the frozen block seed.</p></div><div class="card"><h2>Analysis model</h2><div class="equation">Y<sub>mdb</sub> = β₀ + β<sub>A</sub>A<sub>m</sub> + β<sub>L</sub>L<sub>d</sub> + β<sub>Q</sub>Q<sub>d</sub> + β<sub>AL</sub>A<sub>m</sub>L<sub>d</sub> + β<sub>AQ</sub>A<sub>m</sub>Q<sub>d</sub> + b<sub>0b</sub> + b<sub>1b</sub>A<sub>m</sub> + ε<sub>mdb</sub></div><p>Architecture uses sum coding; dropout uses orthogonal linear and quadratic contrasts. Random block effects preserve the within-block pairing.</p></div></div></section>

  <section id="diagnostics" class="panel"><div class="card"><h2>Diagnostic behavior explorer</h2><p class="sub">These are labeled synthetic demonstrations of convergence diagnostics, not OpenSky experiment results.</p><div class="controls"><div class="control"><label for="chainMode">Illustration</label><select id="chainMode"><option value="good">Four stationary chains</option><option value="shift">One shifted chain</option><option value="sticky">Highly autocorrelated chains</option></select></div><div class="readout">Rank R-hat: <b id="rhatDemo">—</b></div><div class="readout">Bulk ESS: <b id="essDemo">—</b></div></div><div id="chainPlot" class="plot tall"></div><p class="notice">Diagnostic values are pedagogical approximations computed in-browser. Publication endpoints must come from genuine independently initialized traces and the Python implementation.</p></div><div class="grid3"><div class="card"><h2>R-hat</h2><p>Report the maximum of rank-normalized bulk and folded split R-hat. A noisy copy of one chain is not an independent chain.</p></div><div class="card"><h2>Bulk ESS</h2><p>Estimate autocorrelation-adjusted information after rank normalization and initial-positive paired truncation.</p></div><div class="card"><h2>Particle ESS</h2><p>SMC ESS monitors weight degeneracy and resampling. It is not interchangeable with MCMC ESS.</p></div></div></section>

  <section id="validation" class="panel"><div class="card"><h2>Validation ladder</h2><p class="sub">The release is intentionally positioned at methods readiness, before empirical outcome claims.</p><div class="ladder"><div class="gate complete"><span class="status">Complete</span><h3>Mathematics</h3><p>Product measure, kernels, stick weights, targets, and diagnostics.</p></div><div class="gate complete"><span class="status">Complete</span><h3>Software</h3><p>Deterministic smoke test, invariant tests, CI, and artifact rebuilds.</p></div><div class="gate pending"><span class="status pending">Pending</span><h3>OpenSky benchmark</h3><p>100 frozen blocks, 600 executions, locked evaluator.</p></div><div class="gate blocked"><span class="status" style="color:var(--coral)">Out of scope</span><h3>Operational RF</h3><p>Receiver recordings, radar pulses, field hardware, or SIGINT validation.</p></div></div></div><div class="card"><h2>Claim audit</h2><table><thead><tr><th>Status</th><th>Defensible statement</th></tr></thead><tbody><tr><td><span class="status">Now</span></td><td>The repository implements two topology-aware Bayesian nonparametric streaming methods and a reproducible paired validation protocol.</td></tr><tr><td><span class="status pending">After execution</span></td><td>The frozen OpenSky experiment estimates architecture, thinning, and interaction effects for prespecified endpoints.</td></tr><tr><td><span class="status" style="color:var(--coral)">Never from these data</span></td><td>Radar-pulse classification, emitter identification, intent, threat status, operational ELINT, or operational SIGINT performance.</td></tr></tbody></table></div></section>

  <section id="resources" class="panel"><div class="card"><h2>Report, protocol, code, and evidence</h2><p class="sub">The PDF is a 26-page APA-style methods and preregistration report. It does not invent an empirical Results section.</p><div class="controls"><a class="btn primary" href="report/OpenSky_Streaming_DPMM_APA_Report.pdf">Open 26-page report</a><a class="btn" href="docs/STATISTICAL_MODEL.md">Statistical model</a><a class="btn" href="docs/EXPERIMENT_PROTOCOL.md">Experiment protocol</a><a class="btn" href="data/experiment_design.csv">Design CSV</a><a class="btn" href="https://github.com/salemmorelli1/OpenSky-Streaming-DPMM">GitHub repository</a></div></div><div class="grid2"><div class="card"><h2>Reproduce locally</h2><pre>python -m venv .venv
source .venv/Scripts/activate
python -m pip install -e ".[test,report]"
python -m pytest
python -m opensky_streaming_dpmm.engine
python scripts/build_site.py
python scripts/build_report.py</pre></div><div class="card"><h2>External sources</h2><table><tr><th>OpenSky API</th><td><a href="https://openskynetwork.github.io/opensky-api/rest.html">Current REST documentation</a></td></tr><tr><th>VI DPMM</th><td><a href="https://projecteuclid.org/journals/bayesian-analysis/volume-1/issue-1/Variational-inference-for-Dirichlet-process-mixtures/10.1214/06-BA104.full">Blei and Jordan (2006)</a></td></tr><tr><th>DP construction</th><td><a href="https://www3.stat.sinica.edu.tw/statistica/j4n2/j4n216/j4n216.htm">Sethuraman (1994)</a></td></tr><tr><th>Diagnostics</th><td><a href="https://arxiv.org/abs/1903.08008">Vehtari et al. (2021)</a></td></tr></table></div></div></section>
</main>
<footer class="footer"><div class="shell"><b>OpenSky Streaming DPMM</b> · Computational statistics methodology · Empirical benchmark pending · No operational SIGINT claim.</div></footer>
<script>
const ink='#dceef8',grid='#203e55',cyan='#39d5ff',mint='#63e6b2',amber='#ffbe4d',coral='#ff7d78',violet='#a78bfa';
const layout={paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{color:ink,family:'Inter,system-ui'},margin:{l:60,r:25,t:35,b:55},xaxis:{gridcolor:grid,zerolinecolor:grid},yaxis:{gridcolor:grid,zerolinecolor:grid},legend:{orientation:'h',y:1.12},hoverlabel:{bgcolor:'#08131f',bordercolor:cyan,font:{color:'white'}}};
const config={displayModeBar:false,responsive:true};
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.panel).classList.add('active');setTimeout(()=>window.dispatchEvent(new Event('resize')),30)}));
function circle(){const raw=+document.getElementById('heading').value,w=((raw%360)+360)%360,a=w*Math.PI/180;document.getElementById('rawHeading').textContent=raw.toFixed(2)+'°';document.getElementById('wrappedHeading').textContent=w.toFixed(2)+'°';document.getElementById('arcHeading').textContent=Math.min(w,360-w).toFixed(2)+'°';const t=Array.from({length:181},(_,i)=>i*2*Math.PI/180);Plotly.react('circlePlot',[{x:t.map(Math.cos),y:t.map(Math.sin),mode:'lines',line:{color:grid,width:5},hoverinfo:'skip'},{x:[0,Math.cos(a)],y:[0,Math.sin(a)],mode:'lines+markers',line:{color:cyan,width:4},marker:{size:[5,14],color:[ink,cyan]},name:'Heading vector'},{x:[1],y:[0],mode:'markers+text',text:['0° / 360°'],textposition:'top right',marker:{size:10,color:amber},name:'Coordinate cut'}],{...layout,xaxis:{...layout.xaxis,range:[-1.35,1.35],scaleanchor:'y'},yaxis:{...layout.yaxis,range:[-1.2,1.2]},showlegend:false,annotations:[{x:Math.cos(a),y:Math.sin(a),text:`(${Math.cos(a).toFixed(3)}, ${Math.sin(a).toFixed(3)})`,showarrow:true,arrowcolor:cyan,font:{color:cyan}}]},config)}
document.getElementById('heading').addEventListener('input',circle);circle();
function sticks(){const a=+document.getElementById('alpha').value,K=+document.getElementById('clusters').value,ks=Array.from({length:39},(_,i)=>i+2),ys=ks.map(k=>Math.pow(a/(1+a),k-1)),r=Math.pow(a/(1+a),K-1);document.getElementById('residual').textContent=r.toExponential(2);document.getElementById('represented').textContent=((1-r)*100).toFixed(3)+'%';Plotly.react('stickPlot',[{x:ks,y:ys,type:'scatter',mode:'lines',line:{color:violet,width:4},fill:'tozeroy',fillcolor:'rgba(167,139,250,.10)',name:'Expected residual'},{x:[K],y:[r],type:'scatter',mode:'markers+text',text:[`K=${K}`],textposition:'top center',marker:{color:amber,size:13},name:'Selected'}],{...layout,xaxis:{...layout.xaxis,title:'Truncation K'},yaxis:{...layout.yaxis,title:'Expected residual mass',type:'log'}},config)}
['alpha','clusters'].forEach(id=>document.getElementById(id).addEventListener('input',sticks));sticks();
document.querySelectorAll('.doe .cell').forEach(c=>c.addEventListener('click',()=>{document.querySelectorAll('.doe .cell').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');const m=c.dataset.method,d=c.dataset.drop;document.getElementById('cellTitle').textContent=`${m==='VI'?'Streaming VI':'Collapsed DP-SMC'} · ${d}% thinning`;document.getElementById('cellText').textContent=(m==='VI'?'Low-latency variational approximation':'Particle posterior comparator with resampling and rejuvenation')+` on the shared ${d}% nested-thinning replay for all 100 frozen blocks.`}));
const u=Array.from({length:60},(_,i)=>((i*73)%101)/101),levels=[0,.15,.30];Plotly.newPlot('maskPlot',levels.map((d,j)=>({x:Array.from({length:60},(_,i)=>i+1),y:u.map(v=>v>=d?j+1:null),mode:'markers',marker:{size:8,color:[cyan,violet,coral][j]},name:`${Math.round(d*100)}%`})),{...layout,xaxis:{...layout.xaxis,title:'Observation index'},yaxis:{...layout.yaxis,title:'Retained set',tickvals:[1,2,3],ticktext:['0%','15%','30%'],range:[.5,3.5]}},config);
function rng(seed){let s=seed>>>0;return()=>{s=(1664525*s+1013904223)>>>0;return s/4294967296}}
function normal(r){return Math.sqrt(-2*Math.log(Math.max(r(),1e-9)))*Math.cos(2*Math.PI*r())}
function chains(){const mode=document.getElementById('chainMode').value,traces=[],n=260;for(let c=0;c<4;c++){let r=rng(2026+c),x=0,arr=[];for(let i=0;i<n;i++){let rho=mode==='sticky'?.97:.35;x=rho*x+Math.sqrt(1-rho*rho)*normal(r);arr.push(x+(mode==='shift'&&c===3?2.7:0))}traces.push(arr)}const means=traces.map(a=>a.reduce((x,y)=>x+y,0)/n),grand=means.reduce((x,y)=>x+y,0)/4,W=traces.reduce((s,a,j)=>s+a.reduce((q,v)=>q+(v-means[j])**2,0)/(n-1),0)/4,B=n*means.reduce((s,m)=>s+(m-grand)**2,0)/3,rh=Math.sqrt(((n-1)*W/n+B/n)/W);let rho1=traces.reduce((s,a)=>{const m=a.reduce((x,y)=>x+y,0)/n;let num=0,den=0;for(let i=0;i<n-1;i++)num+=(a[i]-m)*(a[i+1]-m);for(const v of a)den+=(v-m)**2;return s+num/den},0)/4,ess=Math.min(4*n,4*n*(1-rho1)/(1+rho1));document.getElementById('rhatDemo').textContent=rh.toFixed(3);document.getElementById('essDemo').textContent=Math.round(ess);Plotly.react('chainPlot',traces.map((a,c)=>({x:Array.from({length:n},(_,i)=>i+1),y:a,mode:'lines',line:{width:1.5,color:[cyan,mint,amber,violet][c]},name:`Chain ${c+1}`})),{...layout,xaxis:{...layout.xaxis,title:'Iteration'},yaxis:{...layout.yaxis,title:'Illustrative scalar state'}},config)}
document.getElementById('chainMode').addEventListener('change',chains);chains();
</script>
</body></html>'''


def main() -> None:
    output = ROOT / "index.html"
    output.write_text(HTML, encoding="utf-8", newline="\n")
    print(f"Wrote {output} ({output.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
